[project]
name = "mini-coffee"
version = "0.1.0"
description = ""
authors = [
    {name = "nemkov",email = "mindrobots.nemkov@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.10,<3.14"
dependencies = [
    "pyside6 (>=6.9.0,<7.0.0)",
    "dotenv (>=0.9.9,<0.10.0)"
]

[tool.poetry]
name = "mini_coffee"
packages = [{include = "mini_coffee", from = "src"}]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
<<<<<<< HEAD
mini-coffee = "mini_coffee.main:run"
=======
mini-coffee = "mini_coffee.main:run"
>>>>>>> refs/remotes/origin/main
